import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { ThemeProvider } from "@/components/theme-provider";
import "./globals.css";
import Header from "@/components/Header";
import Banner from "@/components/Banner";
import Script from "next/script";
import { ClerkProvider } from "@clerk/nextjs";
import { Toaster } from "react-hot-toast";
import { ReduxProvider } from "@/components/ReduxProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  leftSideBar,
  mainContent,
}: Readonly<{
  children: React.ReactNode;
  leftSideBar: React.ReactNode;
  mainContent: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en" suppressHydrationWarning>
        <head>
          <Script
            src={`https://www.googletagmanager.com/gtag/js?id=G-0RKC8Z01C6`}
            strategy="afterInteractive"
          />
          <Script
            id="gtag-init"
            strategy="afterInteractive"
            dangerouslySetInnerHTML={{
              __html: `
              window.dataLayer = window.dataLayer || [];
              function gtag(){dataLayer.push(arguments);}
              window.gtag = gtag;
              gtag('js', new Date());
              gtag('config', 'G-0RKC8Z01C6', {
                page_path: window.location.pathname,
              });
            `,
            }}
          />
        </head>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <ThemeProvider
            attribute="class"
            defaultTheme="light"
            enableSystem
            disableTransitionOnChange
          >
            <ReduxProvider>
              <div className="bg-light-background dark:bg-background">
                <div className="container mx-auto relative max-md:static">
                  <div className="h-8 max-md:h-0"></div>
                  <Header />
                  <div className="h-24 max-md:hidden"></div>
                  {leftSideBar}
                  <Banner />
                  <div className="flex justify-end max-md:block max-md:px-5 pr-20 relative -mt-28 max-md:-mt-0 z-10">
                    <div className="flex flex-col w-3/5 max-md:w-full">
                      {mainContent}
                      {children}
                    </div>
                  </div>
                </div>
                <Toaster />
              </div>
            </ReduxProvider>
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
